// <auto-generated />
namespace Likkle.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Updated_NotificationSetting_Entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updated_NotificationSetting_Entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201611081540394_Updated_NotificationSetting_Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
