// <auto-generated />
namespace Likkle.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class User_Entity_Added_And_Automatic_Db_Seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Entity_Added_And_Automatic_Db_Seed));
        
        string IMigrationMetadata.Id
        {
            get { return "201610301120071_User_Entity_Added_And_Automatic_Db_Seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
