// <auto-generated />
namespace Likkle.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class VisibleToThePublic_NewFieldForGroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VisibleToThePublic_NewFieldForGroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201711011430551_VisibleToThePublic_NewFieldForGroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
